[tool.black]
line-length = 120

[tool.isort]
profile = "black"
lines_between_sections = 0
force_sort_within_sections = true
honor_case_in_force_sorted_sections = true
skip = [".git", ".venv"]
line_length = 120
